<div class="col-md-6 mb-3"><label class="form-label">Business name</label><input name="business_name" class="form-control" value="{{ old('business_name', $tenant->business_name) }}" required></div>
<div class="col-md-6 mb-3"><label class="form-label">Trade name</label><input name="trade_name" class="form-control" value="{{ old('trade_name', $tenant->trade_name) }}"></div>
<div class="col-md-12 mb-3"><label class="form-label">Registered address</label><textarea name="registered_address" class="form-control" required>{{ old('registered_address', $tenant->registered_address) }}</textarea></div>
<div class="col-md-4 mb-3"><label class="form-label">TIN</label><input name="tin" class="form-control" value="{{ old('tin', $tenant->tin) }}" required></div>
<div class="col-md-4 mb-3"><label class="form-label">Taxpayer type</label><select name="taxpayer_type" class="form-select" required><option value="VAT" @selected(old('taxpayer_type', $tenant->taxpayer_type) === 'VAT')>VAT</option><option value="NON_VAT" @selected(old('taxpayer_type', $tenant->taxpayer_type) === 'NON_VAT')>NON_VAT</option></select></div>
<div class="col-md-4 mb-3"><label class="form-label">BIR RDO code</label><input name="bir_rdo_code" class="form-control" value="{{ old('bir_rdo_code', $tenant->bir_rdo_code) }}"></div>
<div class="col-md-4 mb-3"><label class="form-label">Contact name</label><input name="contact_name" class="form-control" value="{{ old('contact_name', $tenant->contact_name) }}"></div>
<div class="col-md-4 mb-3"><label class="form-label">Contact email</label><input name="contact_email" type="email" class="form-control" value="{{ old('contact_email', $tenant->contact_email) }}"></div>
<div class="col-md-4 mb-3"><label class="form-label">Contact phone</label><input name="contact_phone" class="form-control" value="{{ old('contact_phone', $tenant->contact_phone) }}"></div>
<div class="col-md-4 mb-3"><label class="form-label">License status</label><select name="license_status" class="form-select">@foreach (['trial','active','grace_period','suspended','disabled'] as $status)<option value="{{ $status }}" @selected(old('license_status', $tenant->license_status ?: 'trial') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select></div>
<div class="col-md-4 mb-3"><label class="form-label">Subscription expiry</label><input name="subscription_expires_at" type="date" class="form-control" value="{{ old('subscription_expires_at', optional($tenant->subscription_expires_at)->format('Y-m-d')) }}"></div>
<div class="col-md-4 mb-3"><label class="form-label">Grace period days</label><input name="grace_period_days" type="number" min="0" class="form-control" value="{{ old('grace_period_days', $tenant->grace_period_days ?? 0) }}"></div>
<div class="col-md-6 mb-3"><label class="form-label">Logo path</label><input name="logo_path" class="form-control" value="{{ old('logo_path', $tenant->logo_path) }}"></div>
<div class="col-md-6 mb-3"><label class="form-label">Invoice footer</label><textarea name="invoice_footer" class="form-control">{{ old('invoice_footer', $tenant->invoice_footer) }}</textarea></div>
<div class="col-md-12 mb-3"><div class="form-check"><input type="hidden" name="active" value="0"><input id="active" name="active" value="1" type="checkbox" class="form-check-input" @checked(old('active', $tenant->active ?? true))><label for="active" class="form-check-label">Active tenant</label></div></div>
